### ISSUE TITLE
Item is already present is not catched

### ISSUE THREAD

**Issue by Paulpanther** [Paulpanther/CastlesAndDragons#1]
```
[WebSocketWorker-12] ERROR org.java_websocket.drafts.Draft_6455 - Runtime exception during onWebsocketMessage
java.lang.IllegalArgumentException: Item is already present in grid
  at com.paulmethfessel.cad.model.Grid.set(Grid.kt:19)
  at com.paulmethfessel.cad.model.Grid.setItem(Grid.kt:35)
  at com.paulmethfessel.cad.model.Grid.setItem(Grid.kt:30)
  at com.paulmethfessel.cad.server.Game.onMove(Game.kt:39)
  at com.paulmethfessel.cad.server.Game.onMessage(Game.kt:67)
  at com.paulmethfessel.cad.server.Clients$onMessage$1.invoke(Clients.kt:61)
  at com.paulmethfessel.cad.server.Clients$onMessage$1.invoke(Clients.kt:10)
  at com.paulmethfessel.cad.server.Clients.notifyListeners(Clients.kt:85)
  at com.paulmethfessel.cad.server.Clients.onMessage(Clients.kt:61)
  at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:648)
  at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:858)
  at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:792)
  at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
  at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
  at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1021)
  at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1003)
Sending: type=left;client=3,M
Sending: type=left;client=3,M
Sending: type=left;client=3,M
Error: java.lang.IllegalArgumentException: Item is already present in grid
```

**Comment by Paulpanther** [comment]
Fixed with efdce9d332d65a9d42a81d0e3aae9af8e15031de
